### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/renoki-co/php-k8s/pull/402/commits/0dd9425f2012cfb02d5360518f0f4952b03a1c5c?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/php-k8s.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "renoki-co/php-k8s": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by cuppett** [comment]
@rennokki Let me know if this needs work, I'm happy to get the dependencies, code and CI stuff all up to snuff for Laravel 11.

Before that, I'd recommend merging #380 so we can get the first wave of bumps for k8s, deprecated dependencies and other tooling in.

**Comment by decnorton** [comment]
@rennokki It looks as if the latest on master (w/ Laravel 11 support) is passing CI, is there anything else that's preventing a new version from being tagged that we can help with?

**Pull request merged**
