### PR TITLE
feat: add a factory to create an instance from the current kubeconfig files

### PR DESCRIPTION
**Pull request by dunglas**
This PR adds a new factory method using the `KUBECONFIG` environment variable, and the default `~/.kube/config` file when not set.
This is convenient when the environment is already properly configured (ex: CLI commands).

By the way, it could be nice to mark the existing factory methods as static, but I didn't change that because it's a (tiny) BC break.

Cheers!

### CODE REVIEW

**Comment by rennokki** [comment]
So I've been reviewed this neat feature, and I should say that I changed the approach.

The authentication works by user selection, not by calling factories, like users calling `fromKubeconfigFile()` if they want this type of authentication. I chose that because it's easier to opt-in by method, which is how [laravel-php-k8s](https://github.com/renoki-co/laravel-php-k8s/blob/master/src/KubernetesCluster.php#L52-L58) does that in Laravel.

Instead of having a factory that should be called, the user would rather call by himself `->withKubeconfigVariable()` and then everything should proceed as usual.

Good props for having a raw implementation I could segment. 👍

**Comment by dunglas** [comment]
That's weird design to create a non-valid object and then update its state to create a valid one isn't it? The factory pattern allows to ensure that the created objects always have valid states.

Wouldn't it be better to change the existing method instead? The laravel provider could use the factory methods easily.

**Comment by rennokki** [comment]
This feature is useful. It can be merged like this for 2.0 and eventually plan a 3.0 with a better implementation?

**Comment by dunglas** [comment]
Ok for me, I'll update the PR.

**Pull request merged**
